### ISSUE TITLE
[Developer Experience]: Add Cypress Test for 'Contact Us' Image Component

### ISSUE THREAD

**Issue by chadstewart** [TechIsHiring/techishiring-website#131]
## Developer Experience Issue

**Please describe your Developer Experience Issue.**
A clear and concise description of what the problem is. Ex. I have an issue when [...]

Add Cypress test for 'Contact Us' Image Component.

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Add any considered drawbacks.

Add a Cypress test that would:

- Test that the image renders properly on Desktop
- Test that a background image renders properly on mobile

**Describe alternatives you've considered**

n/a

**Teachability, Documentation, Adoption, Migration Strategy**
If you can, explain how users will be able to use this and possibly write out a version in the docs.
Maybe a screenshot or design?

n/a

**Comment by Nkiriobasi** [comment]
I'll work on this

**Comment by ciradu2204** [comment]
@chadstewart can I work on this?

**Comment by chadstewart** [comment]
> @chadstewart can I work on this?

Sure @ciradu2204, feel free!

**Comment by ciradu2204** [comment]
Great, thanks

**Comment by chadstewart** [comment]
Resolved in #141
