### ISSUE TITLE
[BUG]: unwanted text in the landing page 

### ISSUE THREAD

**Issue by dev-phantom** [TechIsHiring/techishiring-website#142]
There's an unwanted text "y" in the footer
## Current Behavior
![Screenshot_20230516-165158](https://github.com/TechIsHiring/techishiring-website/assets/72051159/c0d87859-6277-453d-9021-b59fd6cd9041)

## Steps to Reproduce

1.
2.
3.
4.

**Comment by dev-phantom** [comment]
@chadstewart I'm so sorry for assigning you
It seems it got assigned when I was opening the issue
Do I close it and reopen a new one?

**Comment by chadstewart** [comment]
It's cool, no problem.

This should be resolved in #140
