### ISSUE TITLE
[Feature]: Add Zod validation on request object to process-email route

### ISSUE THREAD

**Issue by chadstewart** [TechIsHiring/techishiring-website#144]
## Feature Request

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I have an issue when [...]

Currently, there's a route in src/pages/api/ called process-email that sends the contents of the Contact Us form to SendGrid. That route expects a json object with name, email and message but there is no validation for that object.

There needs to be validation done to that request.

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Add any considered drawbacks.

Use Zod to ensure that the request object that comes in, has name, email and message so that it can be used when sending the email.

They should not be missing, empty or malformed.

Name: Be a string
Email: Be an email address
Message: Be a string

**Describe alternatives you've considered**

There is Zod validation on the Contact Form component that we may be able to move into a utility function and then use them in the same place. This might be too early of an abstraction but this is potentially a solution.

**Teachability, Documentation, Adoption, Migration Strategy**
If you can, explain how users will be able to use this and possibly write out a version in the docs.
Maybe a screenshot or design?

n/a

**Comment by Sadaf-A** [comment]
Greetings, @chadstewart I have Opened a PR which fixes this issue please have a look

**Comment by chadstewart** [comment]
Closing this issue because it was resolved in #157
