### ISSUE TITLE
Add a loader when the app is fetching data

### ISSUE THREAD

**Issue by jorgeruvalcaba** [TechIsHiring/techishiring-website#21]

**Comment by chadstewart** [comment]
Thanks much! I honestly need to rework how getting tweets work but this is definitely a UX thing I need to address!

**Comment by dev-phantom** [comment]
@chadstewart can i work on this or it has been resolved

**Comment by chadstewart** [comment]
> @chadstewart can i work on this or it has been resolved

Sure, go ahead and work on this!

**Comment by dev-phantom** [comment]
this issue has been fixed in my next PR

**Comment by chadstewart** [comment]
> this issue has been fixed in my next PR

Okay, no problem. Please ensure to add the issue in your PR and add a note in the description to say that you fixed this issue in that PR so it doesn't get lost.
