### ISSUE TITLE
Add Vitest, React Testing Library and Cypress

### ISSUE THREAD

**Issue by chadstewart** [TechIsHiring/techishiring-website#29]
## Feature Request

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I have an issue when [...]

There is currently no automated tests for the project.

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Add any considered drawbacks.

We should add Vitest, React Testing Library and Cypress to the project.

**Describe alternatives you've considered**

Haven't considered any alternatives at this time.

**Teachability, Documentation, Adoption, Migration Strategy**
If you can, explain how users will be able to use this and possibly write out a version the docs.
Maybe a screenshot or design?

n/a

**Comment by TAKANOME-DEV** [comment]
Hey @chadstewart, I saw a couple of issues about testing and it seems like you're not really sure how to structure the tests. 
I haven't checked the project yet, but I saw that you set up the atomic design like you did in insights.opensauced.pizza :pizza: 
Do you want to test each component (organism :thinking: ) in isolation + unit tests or just an e2e test?

**Comment by chadstewart** [comment]
> Hey @chadstewart, I saw a couple of issues about testing and it seems like you're not really sure how to structure the tests. I haven't checked the project yet, but I saw that you set up the atomic design like you did in insights.opensauced.pizza pizza Do you want to test each component (organism thinking ) in isolation + unit tests or just an e2e test?

So honestly, I'm really thinking about mostly e2e tests for the components and unit tests for whatever business logic I have that makes sense. I honestly don't see the value of testing components that's mostly markup.

What are your opinions on testing an Atomic Design code base?

**Comment by TAKANOME-DEV** [comment]
>So honestly, I'm really thinking about mostly e2e tests for the components and unit tests for whatever business logic I have that makes sense. I honestly don't see the value of testing components that's mostly markup.
>
Totally agree with you.
> What are your opinions on testing an Atomic Design code base?
>
I have never done it and I'm new to Atomic Design :sweat_smile: I think we don't need to test each atom, molecule etc, we can build them and test them with Storybook. Checkout [jest integration with Storybook](https://storybook.js.org/addons/@storybook/addon-jest)

**Comment by chadstewart** [comment]
> > So honestly, I'm really thinking about mostly e2e tests for the components and unit tests for whatever business logic I have that makes sense. I honestly don't see the value of testing components that's mostly markup.
> 
> Totally agree with you.
> 
> > What are your opinions on testing an Atomic Design code base?
> 
> I have never done it and I'm new to Atomic Design 😅 I think we don't need to test each atom, molecule etc, we can build them and test them with Storybook. Checkout [jest integration with Storybook](https://storybook.js.org/addons/@storybook/addon-jest)

I'll check this out! If anything, for now we can focus on e2e tests unless it's specific business logic. This will be interesting to go through!

**Comment by TAKANOME-DEV** [comment]
Great, assign it to me and I'll set up the test environments.
Btw, just curious to know about why you choose Cypress over Playwright :thinking:

**Comment by chadstewart** [comment]
> Great, assign it to me and I'll set up the test environments. Btw, just curious to know about why you choose Cypress over Playwright 🤔

Didn't know about Playwright before I made the choice about Cypress. Just heard of it a few weeks ago and thought about considering it.

We can try out Playwright if you're interested in it. I think we're at the point of the project where we don't have to worry too much about committing to a technology.
