### ISSUE TITLE
Update Header Component

### ISSUE THREAD

**Issue by chadstewart** [TechIsHiring/techishiring-website#34]
## Feature Request

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I have an issue when [...]

The header needs to be updated to the new design.

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Add any considered drawbacks.

![www figma com_file_AHf38Z5LQ4v1YBIgJv0tsM_TechIsHiring_node-id=128%3A550 t=ItybLH9XnPZ96T8A-0](https://user-images.githubusercontent.com/11777161/216629170-2fa26e5f-f158-425e-a5ae-ae8d5b15135e.png)

The component is located in here: https://www.figma.com/file/AHf38Z5LQ4v1YBIgJv0tsM/TechIsHiring?node-id=151%3A571&t=ItybLH9XnPZ96T8A-0

**Describe alternatives you've considered**

n/a

**Teachability, Documentation, Adoption, Migration Strategy**
If you can, explain how users will be able to use this and possibly write out a version in the docs.
Maybe a screenshot or design?

n/a

**Comment by hokagedemehin** [comment]
I will like to take this up. if that is ok

**Comment by chadstewart** [comment]
> I will like to take this up. if that is ok

Sure, no problem. Thanks for taking this up!

**Comment by hokagedemehin** [comment]
Working on it. Should make a PR soon

**Comment by chadstewart** [comment]
Completed by way of #63.
