### ISSUE TITLE
Add Hero Component

### ISSUE THREAD

**Issue by chadstewart** [TechIsHiring/techishiring-website#35]
## Feature Request

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I have an issue when [...]

A hero component needs to be created for use throughout the project.

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Add any considered drawbacks.

A hero component that can take in an image and some text.

**Describe alternatives you've considered**

A single component might not be the best abstraction at the moment so it might make sense to split all the types of hero components currently in the project into separate components.

Check out the pages here for the current hero components: https://www.figma.com/file/AHf38Z5LQ4v1YBIgJv0tsM/TechIsHiring?node-id=151%3A571&t=ItybLH9XnPZ96T8A-0

**Teachability, Documentation, Adoption, Migration Strategy**
If you can, explain how users will be able to use this and possibly write out a version in the docs.
Maybe a screenshot or design?

n/a

**Comment by HassanShanJava** [comment]
Hi, I would like to be assigned this task if it's open. Please have a look at my profile if it helps your decision. I will use tailwindcss and nextjs

**Comment by chadstewart** [comment]
> Hi, I would like to be assigned this task if it's open. Please have a look at my profile if it helps your decision. I will use tailwindcss and nextjs

Hey, what's up? No need for me to review your profile. Go ahead and work on the component. Feel free to make a PR whenever you can!
