### ISSUE TITLE
Add 'Why Choose TechIsHiring?' Component

### ISSUE THREAD

**Issue by chadstewart** [TechIsHiring/techishiring-website#36]
## Feature Request

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I have an issue when [...]

Add a new component to the landing page that's a brief summary of TechIsHiring.

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Add any considered drawbacks.

![www figma com_file_AHf38Z5LQ4v1YBIgJv0tsM_TechIsHiring_node-id=151%3A571 t=ItybLH9XnPZ96T8A-0](https://user-images.githubusercontent.com/11777161/216637881-985c30d2-4313-4149-92c8-1b976f001c13.png)

![www figma com_file_AHf38Z5LQ4v1YBIgJv0tsM_TechIsHiring_node-id=151%3A571 t=ItybLH9XnPZ96T8A-0 (1)](https://user-images.githubusercontent.com/11777161/216638265-702a5634-5c2d-47ae-918d-e2a2251a5138.png)
d5d-bdee-9696bd7867b6.png)

The components can be found here: https://www.figma.com/file/AHf38Z5LQ4v1YBIgJv0tsM/TechIsHiring?node-id=151%3A571&t=ItybLH9XnPZ96T8A-0

**Describe alternatives you've considered**

n/a

**Teachability, Documentation, Adoption, Migration Strategy**
If you can, explain how users will be able to use this and possibly write out a version in the docs.
Maybe a screenshot or design?

n/a

**Comment by hokagedemehin** [comment]
This is actually easy and straightforward.

If no one is handling it, I will like to complete this.

Can I go ahead @chadstewart

**Comment by chadstewart** [comment]
Sure, no problem! Go ahead!

**Comment by hokagedemehin** [comment]
@chadstewart currently the hero has a height that is the screen height and so it makes this section **why choose techishiring** really far to reach.

would it be ok if I reduce the height of the hero with this issue that I am working on??

**Comment by chadstewart** [comment]
Yeah, go ahead and fix that. It should be 876px high.

Also, could you fix this issue here: https://github.com/TechIsHiring/techishiring-website/blob/632058845a76ca58d8c46f904e657952690240a8/src/components/molecules/heroSection/Hero.tsx#L12

There's a link to the bg image on figma as opposed to having the image in the project itself. Could you fix that please?

Thanks much.
