### ISSUE TITLE
Update Footer Component

### ISSUE THREAD

**Issue by chadstewart** [TechIsHiring/techishiring-website#38]
## Feature Request

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I have an issue when [...]

Update Footer to new design.

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Add any considered drawbacks.

![www figma com_file_AHf38Z5LQ4v1YBIgJv0tsM_TechIsHiring_node-id=128%3A550 t=ItybLH9XnPZ96T8A-0 (4)](https://user-images.githubusercontent.com/11777161/216640483-48303839-3b4d-4efe-a668-49eb2211fae3.png)

![www figma com_file_AHf38Z5LQ4v1YBIgJv0tsM_TechIsHiring_node-id=128%3A550 t=ItybLH9XnPZ96T8A-0 (3)](https://user-images.githubusercontent.com/11777161/216640501-ce19c004-1db1-43a5-bcdc-c011ec9877e1.png)

Check out the components here: https://www.figma.com/file/AHf38Z5LQ4v1YBIgJv0tsM/TechIsHiring?node-id=151%3A571&t=ItybLH9XnPZ96T8A-0

**Describe alternatives you've considered**

n/a

**Teachability, Documentation, Adoption, Migration Strategy**
If you can, explain how users will be able to use this and possibly write out a version in the docs.
Maybe a screenshot or design?

n/a

**Comment by hokagedemehin** [comment]
I will like to take this up, if possible.

Thanks

**Comment by chadstewart** [comment]
Sure, no problem! Go ahead!
