### ISSUE TITLE
Update About us page

### ISSUE THREAD

**Issue by chadstewart** [TechIsHiring/techishiring-website#39]
## Feature Request

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I have an issue when [...]

Update About us Page to new design.

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Add any considered drawbacks.

![www figma com_file_AHf38Z5LQ4v1YBIgJv0tsM_TechIsHiring_node-id=128%3A550 t=ItybLH9XnPZ96T8A-0 (7)](https://user-images.githubusercontent.com/11777161/216642016-d6fc8b4b-e895-4f44-9e61-27e3a1d49e5e.png)

![www figma com_file_AHf38Z5LQ4v1YBIgJv0tsM_TechIsHiring_node-id=128%3A550 t=ItybLH9XnPZ96T8A-0 (6)](https://user-images.githubusercontent.com/11777161/216642036-b60953eb-c876-4b28-8b0a-69684953080e.png)

Check out the components here: https://www.figma.com/file/AHf38Z5LQ4v1YBIgJv0tsM/TechIsHiring?node-id=291%3A2179&t=ItybLH9XnPZ96T8A-0

*Note: The header and footer components will be updated in issues #34 & #38. There will be no need to work on them in this issue 

**Describe alternatives you've considered**

n/a

**Teachability, Documentation, Adoption, Migration Strategy**
If you can, explain how users will be able to use this and possibly write out a version in the docs.
Maybe a screenshot or design?

n/a

**Comment by dev-phantom** [comment]
can i solve this?

**Comment by chadstewart** [comment]
> can i solve this?

Sure, go ahead! Much appreciated!
