### ISSUE TITLE
Add Contact Us Page

### ISSUE THREAD

**Issue by chadstewart** [TechIsHiring/techishiring-website#40]
## Feature Request

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I have an issue when [...]

Add a Contact Us Page

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Add any considered drawbacks.

![www figma com_file_AHf38Z5LQ4v1YBIgJv0tsM_TechIsHiring_node-id=128%3A550 t=ItybLH9XnPZ96T8A-0 (9)](https://user-images.githubusercontent.com/11777161/216644305-abdd7907-dcea-4cc6-9f40-45388dcd0bb6.png)

![www figma com_file_AHf38Z5LQ4v1YBIgJv0tsM_TechIsHiring_node-id=128%3A550 t=ItybLH9XnPZ96T8A-0 (8)](https://user-images.githubusercontent.com/11777161/216644314-8e4a8f65-cd94-40e8-99f2-c26de6c1138f.png)

Check out the component here: https://www.figma.com/file/AHf38Z5LQ4v1YBIgJv0tsM/TechIsHiring?node-id=288%3A1549&t=ItybLH9XnPZ96T8A-0

*Note: The header and footer components will be updated in issues https://github.com/TechIsHiring/techishiring-website/issues/34 & https://github.com/TechIsHiring/techishiring-website/issues/38. There will be no need to work on them in this issue

**Describe alternatives you've considered**

n/a

**Teachability, Documentation, Adoption, Migration Strategy**
If you can, explain how users will be able to use this and possibly write out a version in the docs.
Maybe a screenshot or design?

n/a

**Comment by dev-phantom** [comment]
please can i get assigned to this?

**Comment by chadstewart** [comment]
> please can i get assigned to this?

Hey @dev-phantom, sure no problem! Thanks for taking on this issue!

**Comment by chadstewart** [comment]
Was resolved with issue #53.
