### ISSUE TITLE
Update API Layer with Tanstack Query

### ISSUE THREAD

**Issue by chadstewart** [TechIsHiring/techishiring-website#42]
## Feature Request

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I have an issue when [...]

After learning about all the benefits of Tanstack Query, I'd like to remove the custom React Hook that handles API requests and replace it with Tanstack Query. I'd also like to update the API Layer and remove code that will no longer be used.

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Add any considered drawbacks.

The API Layer has a custom React Hook that handles working with API's. I'd like to remove that and effectively replace it with Tanstack Query. There are also several 'guides' in the project on how to use the API Layer that would need to be updated as well. Because of changes to what TechIsHiring uses, the API Layer will likely be underutilized but I would still like to have this updated and in place for future use (I've already found value leveraging the API Layer and the guides I wrote in the project to use it).

Also like to remove the Axios mostly through the advice of @JacobMGEvans.

**Describe alternatives you've considered**

n/a

**Teachability, Documentation, Adoption, Migration Strategy**
If you can, explain how users will be able to use this and possibly write out a version in the docs.
Maybe a screenshot or design?

n/a

**Comment by royanger** [comment]
Is this is reference to src/lib/api/hooks/useApi.tsx? From what I can see its only used in /src/components/molecules/subscribe-to-newsletter/subscribe-to-newsletter.tsx and that's as a mutation (sending a subscriber email to Revue).

I think that Tanstack Query is absolutely amazing, but I also don't think it nets you any value here unless you wanted to started having it handle queries. This is a pretty simple mutation and it success doesn't require a query invalidation+update). 

If you are thinking of adding some queries (think like a list of blog posts, etc) then the switch would definitely make sense.

I think where you could see more benefit would be removing the hook and shifting everything to a serverless function. I see you have one, but there is still lots of logic client side. I think client side you could do a simple fetch and pass the email to the serverless function and let it do the heavy lifting.

**Comment by chadstewart** [comment]
> Is this is reference to src/lib/api/hooks/useApi.tsx? From what I can see its only used in /src/components/molecules/subscribe-to-newsletter/subscribe-to-newsletter.tsx and that's as a mutation (sending a subscriber email to Revue).
> 
> I think that Tanstack Query is absolutely amazing, but I also don't think it nets you any value here unless you wanted to started having it handle queries. This is a pretty simple mutation and it success doesn't require a query invalidation+update).
> 
> If you are thinking of adding some queries (think like a list of blog posts, etc) then the switch would definitely make sense.
> 
> I think where you could see more benefit would be removing the hook and shifting everything to a serverless function. I see you have one, but there is still lots of logic client side. I think client side you could do a simple fetch and pass the email to the serverless function and let it do the heavy lifting.

Nah, there isn't too much benefit here to use Tanstack Query honestly. Revue's deprecated and all that API logic is no longer needed. I am contemplating adding a CMS to the project for something else but that might be down the line. Honestly, I wanted to add Tanstack Router just to really play around with it and the project seemed like a good enough reason to do so.

The more I think about it, the more you're right about just shifting everything to being a serverless function. Not gonna lie, I just didn't think of when I first wrote everything which is why there's so much client-side code, lol.

I'll probably write up a new issue to do that conversion but thanks much for the input!

**Comment by JacobMGEvans** [comment]
Just a heads up, Query isn't just for API requests, it's great for handling anything async that you find yourself writing loading, error handling, and other custom code to manage the Async behaviors.

**Comment by chadstewart** [comment]
> Just a heads up, Query isn't just for API requests, it's great for handling anything async that you find yourself writing loading, error handling, and other custom code to manage the Async behaviors.

Could you elaborate more on this please?

**Comment by JacobMGEvans** [comment]
> > Just a heads up, Query isn't just for API requests, it's great for handling anything async that you find yourself writing loading, error handling, and other custom code to manage the Async behaviors.
> 
> Could you elaborate more on this please?

@chadstewart It is easier to show you, I hijacked the Query docs "simple" example and changed it from an API call to a plain Promise I made inline, to illustrate it can be used for any async handling: 
https://codesandbox.io/s/ancient-breeze-8qvjzl?file=/src/index.jsx

**Comment by chadstewart** [comment]
Probably gonna hold back from using Tanstack Query for now. Don't need it as yet but will probably implement it later when the project is more mature.
