### ISSUE TITLE
Bug: Cannot view the newsletter page

### ISSUE THREAD

**Issue by TAKANOME-DEV** [TechIsHiring/techishiring-website#45]
## Expected Behavior

When visited [techishiring.com/newsletter](https://www.techishiring.com/newsletter), I expected to see the newsletter page.
## Current Behavior

A 500 error page showed up
![image](https://user-images.githubusercontent.com/79809121/216777273-23096920-809c-4a51-a693-9038e5c16539.png)

## Steps to Reproduce

1. Go to [https://www.techishiring.com](https://www.techishiring.com)
2. Click the newsletter in the header 
3. 500 error page shows up

## Context (Environment)

- Browser: Firefox
- OS: Linux/Ubuntu 22

**Comment by chadstewart** [comment]
Thanks for reminding me @TAKANOME-DEV. I need to work that out as soon as I can! I'll try to get a fix out soon!
