### ISSUE TITLE
Feat: Switching to Material UI from Chakra UI

### ISSUE THREAD

**Issue by hokagedemehin** [TechIsHiring/techishiring-website#46]
## Feature Request

**Is your feature request related to a problem? Please describe.**
I remember some few years back when I was still swaping through different UI libraries, looking for one that I can use for all my web development needs, I came across Chakra UI and fell in love with it almost immediately. Around that same time I was already a fan of Tailwind CSS for obvious reasons, but when I tried to combine these two great libraries, there were clitches here and there. Lots of the components in Chakra UI does not allow custom manipulation to fit my needs so it was very hard to use these two in the same project 

**Describe the solution you'd like**
A switch to Material UI will open the project to more components and will allow better integration with Tailwind CSS [Style library interoperability](https://mui.com/material-ui/guides/interoperability/#tailwind-css)

And did I mention Material UI is written fully in Typescript now, so no type issue will be encountered

What do you think?

**Comment by chadstewart** [comment]
Hey @hokagedemehin. I really appreciate the feature request but I don't think we need to switch to Material UI at this time. Let's continue to stick with Chakra UI.
