### ISSUE TITLE
I would like to build this component

### ISSUE THREAD

**Issue by HassanShanJava** [TechIsHiring/techishiring-website#47]
I have experience with building UI designs using figma, for this component I would like to build it with tailwindcss and nextjs.

Here is my portfolio:
[Portfolio link](https://hassan-shan-portfolio-mern.netlify.app/)

**Comment by chadstewart** [comment]
Thanks so much for your interest! Feel free to make a mention of which components you want to work on in that componentxs issue and assign the issue to yourself.
