### ISSUE TITLE
Add ESLint GitHub Action

### ISSUE THREAD

**Issue by chadstewart** [TechIsHiring/techishiring-website#51]
## Developer Experience Issue

**Please describe your Developer Experience Issue.**
A clear and concise description of what the problem is. Ex. I have an issue when [...]

So there's linting rules for the project that can cause errors that causes the build to break when adding PRs. This was an issue in PR issue #50.

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Add any considered drawbacks.

Thinking of adding a GitHub Action to run linting on the project when code is pushed. I'm not sure if this is the best solution but it's the thing that came to mind first. I'll look into other solutions.

**Describe alternatives you've considered**

We could have pre-commit hooks that'll run linting before pushing the code. Or we could make the linting rules warnings instead of errors so builds won't break on linting rules.

**Teachability, Documentation, Adoption, Migration Strategy**
If you can, explain how users will be able to use this and possibly write out a version in the docs.
Maybe a screenshot or design?

n/a

**Comment by TAKANOME-DEV** [comment]
I think adding an action to test and build the project on each pr is a good thing.

Although, some people (including me) like to configure pre-commit hook while others dislike the idea (found out why -> https://www.youtube.com/watch?v=w0nWe3eqjAc) :sweat_smile:

**Comment by chadstewart** [comment]
> I think adding an action to test and build the project on each pr is a good thing.
> 
> Although, some people (including me) like to configure pre-commit hook while others dislike the idea (found out why -> https://www.youtube.com/watch?v=w0nWe3eqjAc) sweat_smile

Sorry it took so long to get back to you.

Yeah, I've heard the argument against pre-commit hooks specifically. So I've heard Theo elaborate more on his argument where he's against things that are road blocks to getting fast feedback. Pre-commit hooks are an example of that road block because if they fail, you can't push and the things that cause them to fail tend to be things that don't immediately add business value to the project (tests, eslint errors, etc.).

I think in our use case it'd be fine if it's not blocking and just running linting on the project so we don't have to have Engineers explicitly have to run the command. I think the real decision here is if we make linting emit a warning or an error (where the error will block a push). I think we can experiment with both and see which one is a better dev experience.

**Comment by TAKANOME-DEV** [comment]
Sounds good :+1: Feel free to set up the configs :wrench:
