### ISSUE TITLE
Remove arbitrary blockers to deploying code

### ISSUE THREAD

**Issue by chadstewart** [TechIsHiring/techishiring-website#59]
## Developer Experience Issue

**Please describe your Developer Experience Issue.**
A clear and concise description of what the problem is. Ex. I have an issue when [...]

So when the project started and I worked on the project alone, I was used to having some of the tooling emit errors instead of warnings when I worked, such as tsc and linters. Now that the project is public and getting some traction, I don't think that is a good dev experience for contributors so I'd like to reduce the number of hurdles of getting a contribution landed.

Examples of this issue:

#50
#58

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Add any considered drawbacks.

Right now, tsc and eslint will emit errors instead of warnings for any rule violations. That'll cause deployment to break and while you can still merge the code, it won't deploy. Setting those to emit warnings should be fine for now.

I'll also take the time to look at the CI/CD pipeline and see where we can implement this idea as well.

**Describe alternatives you've considered**

n/a

**Teachability, Documentation, Adoption, Migration Strategy**
If you can, explain how users will be able to use this and possibly write out a version in the docs.
Maybe a screenshot or design?

Dunno if there's a teachable moment here other than actually worry about your dev experience! 😂

**Comment by royanger** [comment]
I think that Typescript issues should remain errors. There is value there in avoiding bugs.

In terms of eslint, your current eslint config is:
```
"rules": {
    "comma-dangle": "error",
    "quotes": "error",
    "camelcase": "error",
    "jsx-quotes": "error",
    "semi": "error",
    "indent": ["error", 1]
}
```
Of those, the following are now addressed with prettier:
- `comma-dangle` is covered by the prettier `trailingComma` rule
- 'quotes' and 'jsx-quotes' are covered by the prettier 'singlesQuotes' rule
- 'indent' is partially covered by the prettier 'tabWidth' rule and the prettier rule `"tabs": <false|true>` could be added (false would be spaces, true would be tab characters
- `semi` could be addressed by adding `"semi": true` to the prettier rules

The only rule that is not or can not be covered is the camel case rule.
