### ISSUE TITLE
Update: update the contributing.md for existing contributors

### ISSUE THREAD

**Issue by dev-phantom** [TechIsHiring/techishiring-website#62]
## Developer Experience Issue

**Please describe your Developer Experience Issue.**
A clear and concise description of what the problem is. Ex. I have an issue when [...]
In my last PR a merge conflict was raised that was because i did not fetch upstream before pushing my last commit
 

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Add any considered drawbacks.
update the contributing.md for existing contributors to fetch upstream before creating a new PR or commit 
so as not to result to conflict
**Describe alternatives you've considered**

**Teachability, Documentation, Adoption, Migration Strategy**
If you can, explain how users will be able to use this and possibly write out a version in the docs.
Maybe a screenshot or design?
users can easily copy the command to fetch upstream and also merge upstreams

**Comment by chadstewart** [comment]
> i could update the docs if i get assigned to this

Sure, go ahead and update the docs!
