### ISSUE TITLE
Bug: Background image in contact page is distorted on mobile

### ISSUE THREAD

**Issue by chadstewart** [TechIsHiring/techishiring-website#67]
## Expected Behavior

Background image should be round.

## Current Behavior

Is distorted to be more squished.
![Screenshot from 2023-02-19 12-42-55](https://user-images.githubusercontent.com/11777161/219965427-d3e8e5f0-f01f-45fa-8339-9095e2a467c5.png)

## Steps to Reproduce

1. Go to dev.techishiring.com/contact

**Comment by dev-phantom** [comment]
i think one way around this is to increase the height

**Comment by dev-phantom** [comment]
please sir assign me to this

**Comment by chadstewart** [comment]
> please sir assign me to this

Okay, no problem.

**Comment by dev-phantom** [comment]
@chadstewart this issue has been fixed by someone else 
he'll open a pr now

**Comment by chadstewart** [comment]
> @chadstewart this issue has been fixed by someone else he'll open a pr now

Okay, I'll assign them to this issue then and check their PR.

**Comment by chadstewart** [comment]
I'm closing this issue but please assign yourself to this @devtofunmi. Just really to help maintain the history of the project.

**Comment by devtofunmi** [comment]
@chadstewart i'm unable to assign myself.

**Comment by chadstewart** [comment]
> @chadstewart i'm unable to assign myself.

Assigned this issue to you. Thanks much!

**Comment by devtofunmi** [comment]
@chadstewart you are welcome sir.
