### ISSUE TITLE
Adding a max width on the header

### ISSUE THREAD

**Issue by hokagedemehin** [TechIsHiring/techishiring-website#75]
Currently, the header does not have a max width so it keeps expanding on larger screens and that is not the behaviour we will expect from it.

Right now, I want to address this issue and give the header a max width of 1536 (i.e 2xl in tailwind)

Suggestions are welcomed

@chadstewart your input is also needed for the go-ahead of my idea is fine

**Comment by chadstewart** [comment]
Could you elaborate a bit more on this please? I'm not sure I understand exactly why this is an issue. Are you mentioning the component with the navbar or the component with the hero section?

**Comment by chadstewart** [comment]
I'm not gonna lie, I don't think it's that serious honestly. The site generally wasn't designed for those screen sizes honestly. What do you think @royanger and @TAKANOME-DEV?

**Comment by royanger** [comment]
This was on my radar and I was going to open an Issue on it in the future. I think it needs to be done for the whole site and not just the new hero section. I often just use the `container` class, though that might not be the best solution here (haven't looked yet). We definitely need some sort of max width for larger screens though.

**Comment by TAKANOME-DEV** [comment]
Since the site was not designed for larger screens, I think the best thing to do is add a max-width (i don't know how many) and maybe combine it with the `container` class...

**Comment by royanger** [comment]
The `container` class in Tailwind is a series of `max-width` rules based on screen size, with a widest `max-width` of 1536px. See [https://tailwindcss.com/docs/container](https://tailwindcss.com/docs/container).

**Comment by TAKANOME-DEV** [comment]
> The `container` class in Tailwind is a series of `max-width` rules based on screen size, with a widest `max-width` of 1536px. See https://tailwindcss.com/docs/container.

+1 for using the `container` class :sweat_smile:

**Comment by chadstewart** [comment]
Okay, so I can get behind making the changes but the design might look weird with a max width on larger screens. I'd say what we could do is open a branch and a PR and just experiment with adding either the max width to only the header vs. the entire app. From there, if it doesn't look too weird, then we can just rock with that or if it does then we can make a decision on how to move forward from there seeing exactly how the site looks. Just worried about the design looking weird with a max width honestly.

**Comment by TAKANOME-DEV** [comment]
Sounds good :+1:
