### ISSUE TITLE
Replace background image for Hero Section

### ISSUE THREAD

**Issue by chadstewart** [TechIsHiring/techishiring-website#80]
## Feature Request

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I have an issue when [...]

The hero section has a background image but the image was a direct link to the image in Figma. In #77, that was removed but not replaced. Creating an issue so that it can be replaced with a better implementation.

https://www.figma.com/file/AHf38Z5LQ4v1YBIgJv0tsM/TechIsHiring?node-id=151%3A571&t=NlbZLYNHMZQ0TNCS-0

![Screenshot from 2023-03-12 13-44-23](https://user-images.githubusercontent.com/11777161/224566098-2442a156-9fef-44ed-8ef4-4cae0ec7a54f.png)
![Screenshot from 2023-03-12 13-53-56](https://user-images.githubusercontent.com/11777161/224566314-f6b1643a-80b6-4297-a4b2-b59b222e7a8b.png)

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Add any considered drawbacks.

The previous implementation linked directly to the image in Figma. What would be preferable is to download the background image and just use the asset directly from the project.

Hopefully this shouldn't be too complicated but there might be some Next.js SSR specific details that might be an issue.

**Describe alternatives you've considered**

n/a

**Teachability, Documentation, Adoption, Migration Strategy**
If you can, explain how users will be able to use this and possibly write out a version in the docs.
Maybe a screenshot or design?

Whenever working with assets from Figma, instead of linking to them, you can just download those assets and then add them to the project directly. Best thing to do is ask before moving forward with your PR if you have a question.

**Comment by dev-phantom** [comment]
can i get assigned to this?

**Comment by chadstewart** [comment]
> can i get assigned to this?

Sure, that's no problem. Thanks for taking this on!

**Comment by dev-phantom** [comment]
can i get assigned to this?

**Comment by dev-phantom** [comment]
can i get assigned to this?

**Comment by dev-phantom** [comment]
@chadstewart sir,
the image was downloaded and placed in the public assets folder (the svg file)
should i add it to the `image` folder in the `src` folder ?

**Comment by dev-phantom** [comment]
> > @chadstewart sir, the image was downloaded and placed in the public assets folder (the svg file) should i add it to the `image` folder in the `src` folder ?
> 
> Add it to the `src` folder unless you have a problem doing so.

No sir

**Comment by chadstewart** [comment]
Hey @dev-phantom. Could you please update the alt text for the hero image please? Add the text: "Black male at a desk in front of a computer taking notes."

Thanks so much.
