### ISSUE TITLE
Make contact page mobile bg image visible up to 1024px width

### ISSUE THREAD

**Issue by chadstewart** [TechIsHiring/techishiring-website#90]
## Feature Request

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I have an issue when [...]

Currently, the mobile version of the contact us page has a background image. That background image is not visible between the widths of 768px to 1024 px.

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Add any considered drawbacks.

Update the media query for the background image in `src/components/organisms/contact-content/content-content.tsx` to display up to 1024px.

**Describe alternatives you've considered**

n/a

**Teachability, Documentation, Adoption, Migration Strategy**
If you can, explain how users will be able to use this and possibly write out a version in the docs.
Maybe a screenshot or design?

n/a

**Comment by himanshukrmr** [comment]
Hi @chadstewart may I try this?

**Comment by chadstewart** [comment]
Sure, no problem.
