### ISSUE TITLE
Make Contact Us page functional

### ISSUE THREAD

**Issue by chadstewart** [TechIsHiring/techishiring-website#97]
## Feature Request

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I have an issue when [...]

We have a contact us page but currently it's not functional. We'd like to make the page actually able to send emails to the TechIsHiring email account.

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Add any considered drawbacks.

The web form is built already so it's primarily getting the data out of the form and sending it as an email. This would involve sending all the data as a request to Node instance in Next.js and then sending the email through that Node instance. This makes the serverless function do all the heavy lifting once deployed and keeping the work the client needs to do lightweight.

To actually send the email, we would leverage SendGrid.

**Describe alternatives you've considered**

Right now, SendGrid seems like the most simple way to send an email (admittedly it also seems to be the most popular solution as I haven't built a Contact Us page in years 😂). I saw a few alternatives but I'm going with this. Since the serverless function is acting link a BFF, if we decide to change in the future, the client will be unaffected and all the work can simply take place in the the serverless function.

**Teachability, Documentation, Adoption, Migration Strategy**
If you can, explain how users will be able to use this and possibly write out a version in the docs.
Maybe a screenshot or design?

n/a

**Comment by Shoetan** [comment]
Hi, Chad Stewart is this issue still open? If yes I would like the opportunity to go at it and close it.

**Comment by chadstewart** [comment]
> Hi, Chad Stewart is this issue still open? If yes I would like the opportunity to go at it and close it.

Hey @Shoetan. Thank you for the interest but unfortunately I've already created a PR for this issue. Please feel free to look around the other open issues to see what's available to work on!
